api:
  current:
    version: v1

server:
  port: 8082
  servlet:
    context-path: /medical-report-management-service

web:
  cors:
    allowed-origins: "http://localhost:5000"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical-report-management
    username: skill_up_admin
    password: Skillup1234
    driverClassName: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
      generate-ddl: true
      hibernate:
        show-sql: false
        use_sql_comments: false
        format_sql: false
        ddl-auto: update
  sql:
    init:
      platform: postgres

  # swagger-ui custom path
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
