api:
  current:
    version: v1

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical-report-management
    username: skill_up_admin
    password: Skillup1234
    driverClassName: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
      generate-ddl: true
      hibernate:
        show-sql: false
        use_sql_comments: false
        format_sql: false
        ddl-auto: update
  sql:
    init:
      platform: postgres
